version: '3.8'

services:
  api:
    container_name: tents-booking-api
    image: tents-booking-api
    ports:
      - '3000:3000'

    environment:
      - PORT=${PORT}
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB_USERNAME=${POSTGRES_DB_USERNAME}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_USERNAME}
      - JWT_SECRET=${JWT_SECRET}
      - DEFAULT_USER_EMAIL=${DEFAULT_USER_EMAIL}
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}

    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      # - POSTGRES_DB=testdb
    # volumes:
    #   - ../database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
